[package]
name = "database"
version = "0.1.0"
edition = "2024"

[dependencies]
types = { workspace =  true }
sqlx = { workspace = true }
chrono = {  workspace = true }
uuid = { workspace = true }
tracing = { workspace = true }
