[package]
name = "services"
version = "0.1.0"
edition = "2024"

[dependencies]
database = { workspace = true }
types = { workspace = true }
sqlx = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
