services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: local-mssql
    restart: unless-stopped
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourStrong!Passw0rd"
      MSSQL_PID: "Developer"  # Developer edition has full features for testing
    networks:
      - app

networks:
  app:
    driver: bridge
