[package]
name = "types"
version = "0.1.0"
edition = "2024"

[dependencies]
sqlx = { workspace = true }
chrono = { workspace = true }
serde = { workspace = true }
uuid = { workspace = true }
tokio = { workspace = true }
serde_json = { workspace = true }
axum = { workspace = true }
